config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/Generic-Matomo-Tracker:
      branch: master
      repo: https://github.com/openaire/Generic-Matomo-Tracker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/Generic-Matomo-Tracker git:
        commands:
        - /usr/bin/env sh .sqa/script.polar_supportive_bullfrog.sh
        container: qc.acc_daffodil_radiant_kingfisher
  QC.Doc:
    repos:
      github.com/openaire/Generic-Matomo-Tracker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tide_zealous_iguana.sh
        container: qc.doc_cobalt_mature_raccoon
      github.com/openaire/Generic-Matomo-Tracker git:
        commands:
        - /usr/bin/env sh .sqa/script.ochre_brave_gibbon.sh
        container: qc.doc_flax_sympathetic_mandrill
      github.com/openaire/Generic-Matomo-Tracker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.linen_dreamy_pangolin.sh
        container: qc.doc_marigold_easygoing_sparrow
  QC.Lic:
    repos:
      github.com/openaire/Generic-Matomo-Tracker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fog_mysterious_okapi.sh
        container: qc.lic_pansy_meticulous_turtle
  QC.Sec:
    repos:
      github.com/openaire/Generic-Matomo-Tracker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.maroon_careful_buffalo.sh
        container: qc.sec_emerald_graceful_flounder
  QC.Sty:
    repos:
      github.com/openaire/Generic-Matomo-Tracker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thunder_stubborn_parrot.sh
        container: qc.sty_horizon_cheerful_viper
  QC.Uni:
    repos:
      github.com/openaire/Generic-Matomo-Tracker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_mysterious_elephant.sh
        container: qc.uni_puce_thankful_serval
  QC.Ver:
    repos:
      github.com/openaire/Generic-Matomo-Tracker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.indigo_gentle_stingray.sh
        container: qc.ver_scarlet_easygoing_coyote
timeout: 5400
