config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/Generic-Matomo-Tracker:
      branch: master
      repo: https://github.com/openaire/Generic-Matomo-Tracker
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/Generic-Matomo-Tracker git:
        commands:
        - /usr/bin/env sh .sqa/script.rosewater_loving_hare.sh
        container: qc.acc_gamboge_compassionate_ostrich
  QC.Doc:
    repos:
      github.com/openaire/Generic-Matomo-Tracker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.horizon_anxious_quokka.sh
        container: qc.doc_thistle_peaceful_cheetah
      github.com/openaire/Generic-Matomo-Tracker git:
        commands:
        - /usr/bin/env sh .sqa/script.butter_rational_osprey.sh
        container: qc.doc_cerise_nervous_condor
      github.com/openaire/Generic-Matomo-Tracker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.royal_fair_vulture.sh
        container: qc.doc_aqua_cautious_albatross
  QC.Lic:
    repos:
      github.com/openaire/Generic-Matomo-Tracker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cardamom_optimistic_kiwi.sh
        container: qc.lic_chili_zealous_kingfisher
  QC.Sec:
    repos:
      github.com/openaire/Generic-Matomo-Tracker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flax_sympathetic_orca.sh
        container: qc.sec_currant_thankful_badger
  QC.Sty:
    repos:
      github.com/openaire/Generic-Matomo-Tracker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jet_scrappy_manatee.sh
        container: qc.sty_papaya_humorous_toucan
  QC.Uni:
    repos:
      github.com/openaire/Generic-Matomo-Tracker pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_independent_narwhal.sh
        container: qc.uni_puce_eager_donkey
  QC.Ver:
    repos:
      github.com/openaire/Generic-Matomo-Tracker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.poppy_dedicated_parrot.sh
        container: qc.ver_linen_energetic_horse
timeout: 5400
